### PR TITLE
Env vars config

### PR DESCRIPTION
**Pull request by kristovatlas**
The main feature I wanted to add here was environment variable support for SMTP creds, but I ended up “cleaning up” (changing) lots of other stuff to facilitate testing.

testing:
-build when database file is not present
-build does not damage database if run on database with no records
-build does not damage database file once populated with some data
-added domain to watch successfully
-running core with no watch domains exits peacefully as expected
-running core with one domain results in anticipated results — adds new domains discovered to database, sends email alert about it
-running core with one domain the results of which have all previously been found results in no email sent as expected
-removing one found domain variant from the database with “removeentry"  has anticipated effect on database, and re-running core sees it as a newly found domain variant to email about
-removing the only present watched domain with “removemonitor” has the intended effect. re-running core, it quickly exits without any domains to scan for as expected.
-removing a domain not present in the watch list with “removemonitor" gracefully exits with error message

### CODE REVIEW

**Comment by kristovatlas** [comment]
All testing was done in a MacOS VM.

**Comment by kristovatlas** [comment]
Use of this in util.py is probably not Windows friendly:
```
+BOLD = "\033[1m"
 +END = "\033[0m"
```

This can be addressed fairly easily with another commit, if you wish me to.

**Comment by 0xd34db33f** [comment]
Fine by me if you want to push another commit. I'm not going to be able to run some manual tests on it until tomorrow afternoon/Tues morning anyhow so no rush.

**Comment by kristovatlas** [comment]
Done.

**Comment by 0xd34db33f** [comment]
Little late but looks good

**Pull request merged**
